Huachao/vscode-restclient

README.md, src/httpClient.ts, src/models/configurationSettings.ts
=> Proxy support

package.json, src/controllers/requestController.ts, src/models/configurationSettings.ts, src/views/responseUntitledFileContentProvider.ts
The new feature is working great.  Thanks!
After using this for a bit, I found a couple of things that improve my work.
1.  I set the language automatically when opening a new editor.  I wanted to do this also for reusing the same editor, but I couldn't find an API to do it.
2.  Included request url and elapsed time in the response document
3.  Made the response information into comments which makes it play nice with the language theme and coloring.
Hopefully you can consider these changes.  Thanks!
=> Set language when opening new editor

package.json, src/views/responseUntitledFileContentProvider.ts
This is a change to the open response in Untitled document.
VSCode 1.11 has a new parameter on the API which allows to set the content on opening.
I think this is better for these reasons:
1)  This allows the document to open without a previous undo.  So if you hit undo, you will no longer get a blank document
2)  Since the document is opened in a state of not dirty, you can close the document without the editor giving you a popup asking if you want to close the document.
@Huachao Let me know what you think
=> Switch to new API for opening editor

package.json, src/views/responseUntitledFileContentProvider.ts
vscode 1.12 added a new `showTextDocument` API.
Using this API, it is now possible to reuse the same untitled tab and set the language.
=> use new vscode api to preview untitled document

package.json, src/controllers/environmentController.ts, src/models/configurationSettings.ts
This is such a minor nitpick but it feels a bit distracting for me when i'm editing files that completely unrelated to REST client but that status bar switcher is always present 😄 
This pull request adds `showStatusBarItem` boolean parameter configurable from settings.
Since we can switch environments via command palette anyway we aren't losing in functionality with this new config param set to `false`.
=> Allow hiding status bar item via settings

README.md, package.json, src/constants.ts, src/extension.ts, src/httpElementFactory.ts, src/variableProcessor.ts, test/aadToken.http, test/tests.http
No more copying AAD tokens from the portal or other sources :-)
**`{{$aadToken}}`** &ndash; Get token for home directory of the signed-in user
**`{{$aadToken 00000000-0000-0000-0000-000000000000}}`** &ndash; Get token for directory using tenant ID
**`{{$aadToken contoso.com}}`** &ndash; Get token for directory using domain
**`{{$aadToken new contoso.com}}`** &ndash; Force re-auth and don't reuse tokens across requests
**`{{$aadToken public|cn|de|us|ppe}}`** &ndash; Get token for specific cloud (otherwise implied from URL)
**`F1 > Rest Client: Clear AAD token cache`** &ndash; Clear the in-memory token cache (or restart Code)
=> Add built-in support for Azure AD auth

src/documentLinkProvider.ts, src/extension.ts, src/workspaceUtility.ts
This PR adds support for [Visual Studio Live Share](http://aka.ms/vsls) to the document link provider, by ensuring that URI construction is done using the VS Code APIs which preserve the correct scheme. This is necessary because "guests" within a Live Share session see remote files using the `vsls:` scheme, whereas the the host (and non-Live Share users) sees files using the `file:` scheme. Therefore, this change preserves the existing behavior, while allowing REST Client users to click on `< foo.js` links within the context of a collaboration session 🚀 Specifically, this PR makes the following two changes:
1. Use `Uri.toString()` as opposed to `Uri.fsPath`, since the later strips the `Uri`'s scheme, which removes the `vsls:` portion that is critical for Live Share.
2. Use `Uri.parse()` …
=> [Document Link Provider] Adding Visual Studio Live Share support

src/httpClient.ts
Only the first one in ignore host(with port) take effect in "rest-client.excludeHostsForProxy".
=> Fix bug to exclude hosts(with port) for proxy

src/variableDiagnosticsProvider.ts
This is a follow-up to #187, since I forgot to limit the variable linting to local files as well, and Live Share handles "remoting" diagnostics from the host to the guest.
// CC @Huachao
=> [Live Share] Limiting linting to local files

README.md, package.json, src/httpClient.ts, src/httpRequestParser.ts, src/models/configurationSettings.ts
This adds the feature in #205 by adding the following settings:
+ defaultAccept
+ defaultAcceptCharset
+ defaultAcceptDatetime
+ defaultAcceptEncoding
+ defaultAcceptLanguage
+ defaultAccessControlRequestHeaders
+ defaultAccessControlRequestMethod
+ defaultAuthorization
+ defaultCacheControl
+ defaultContentType
+ defaultCookie
+ defaultHost
+ defaultOrigin
+ defaultUserAgent
=> Default headers support

src/utils/httpClient.ts
Hey there! about my previous pull request #206, this is a small bug fix.
While doing `GET http://some.domain` and having a default `Host` header,
it'd add a wrong Host header which wouldn't work for the request in progress.
=> Do not add Host header if url already has one

package.json, src/controllers/responseController.ts, src/extension.ts
Fixes issue #300 
Added button to copy response body since CMD+C does not work for me in the latest version
=> add copy-reponse-body [#300]

README.md, src/utils/httpVariableProviders/systemVariableProvider.ts
This PR attempts to add support for the following scenario:
``` json
{
"custom_date": "{{$datetime 'YYYY-MM-DD'}}"
}
```
I've also updated the README. I haven't made a VS Code extension before so I haven't ran these changes locally. If someone could give me a few pointers or test the branch for me I'd really appreciate it.
=> Custom date formats

src/utils/httpVariableProviders/environmentVariableProvider.ts
Per issue #342, changes environment variable provider to check environment variables for values like {{$shared [xyz]}}, and if found attempts to get shared variable with name [xyz]. 
Added new error for trying to find a shared variable and not finding one. 
Added to README to reflect new functionality. 
This is my first contribution so I'm very open to corrections/advice!
=> Allow environment variables to reference shared variables

package.json
Added list of missing commands to activationEvents entry
=> fix(package.json): fix command `rest-client-*` not found error

README.md, package-lock.json, package.json, src/utils/auth/awsSignature.ts, src/utils/httpClient.ts, src/utils/misc.ts
Thanks for this awesome extension!
I've added support for AWS Signature version 4 authentication. This resolves #281. I assume that this would be welcomed since that issue is still open.
=> AWS Signature version 4 authentication

src/utils/userDataManager.ts
I am a Linux user.
Linux users hate when people put dotfiles in the HOME folder.
I noticed your awesome extension <3 puts its folder in the HOME folder.
I implemented backwards-compatible support for the XDG directory specification[1].
In the case `~/.rest-client` exists, we continue to use that folder. Otherwise, we use both `XDG_CACHE_HOME/rest-client` and `XDG_CONFIG_HOME/rest-client`.
So in my case as a previous user, I would just delete the current folder, and have the extension use the paths because I have those variables defined, as do most Linux users.
1: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
=> Add support for the XDG directory specification

README.md
Mention that the extension only works if the file has .http extension. This was not clear for me when I installed it, needed to figure out from the screenshots.
=> README.md: update usage

src/utils/httpClient.ts
Server sends me response as 
```
{
"text": "\u0022text\u0022"
}
```
My expectation was that decodeEscapedUnicodeCharacters will convert it to
```
{
"text":"\"text\""
}
```
But result was 
`{"text":""text""}`
with invalid json format errors. 
Curl + jq handles that kind of situation perfectly.
So, small pr to fix that behaviour
=> Escape quotes for decodeEscapedUnicodeCharacters

README.md
Hi, I readlly love this extension so am reading documentation and source code.
I found some trivial typos so just in case I fixed them.
=> Fix some trivial errors in README.md 

src/views/httpResponseWebview.ts
Links inside the a JSON response are not displayed properly because JSON encodes strings.
This fix displays the original url but the underlying link is using the parsed string as the link `href` property.
This is an example JSON response that has this problem:
```
{
"authenticateURL": "https://example.com/auth?reg_code=XLMKJDK\u0026mso_id=ATT",
"expires": 1592867389703
}
```
The parsed link should be `https://example.com/auth?reg_code=XLMKJDK&mso_id=ATT`.
=> Fix broken links in JSON responses

src/providers/documentLinkProvider.ts, src/utils/httpRequestParser.ts
this is part of an issue I've raised, maybe missing something but I tested and it seemed to work :)
=> processing variables from external file

src/utils/httpVariableProviders/systemVariableProvider.ts
This extension just supports `.env` files that are on the same folder of the `.http` file.
With this change, the extension will search for `.env` files on parent folders until it finds one.
closes #690
=> Search for .env files on parent folders

src/extension.ts
This PR simply updates the document selector that is used to register the HTTP language services. By using a `*` scheme, this enables support for HTTP files stored in arbitrary file systems. For example, the [GistPad](https://aka.ms/gistpad) extension allows editing files that are stored in GitHub Gists and repos, and with this change, you can edit/send requests from them.
=> Updating document selector to support virtual file systems

snippets/http.json
write a multipart/form-data request by hand is difficult，so should add a snippet to generate a demo
eg
```
POST url HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary
--WebAppBoundary
Content-Disposition: form-data; name="field-name"
field-value
--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="file-name.txt"
< ./relative/path/to/local_file.txt
--WebAppBoundary--
```
=> add snippet for multipart/form-data request

src/utils/aadV2TokenProvider.ts
1. include scopes in cache key
different network request may need token with different scopes , so include scopes in cache key
2. include original requested scopes also in cache scope
Sometime token is missing requested scopes.
When next request is sent with same scope application is asking for re authentication.
Including original scopes in saved scopes fixes that
=> Update azure ad token caching

src/utils/mimeUtility.ts
I create this PR to deals with the following issue.
When working with some AWS API, you have to use the "application/x-amz-json-1.1" content type. 
The issue is this content type is not recognized as JSON and so, you can not bind the result to variable. 
Instead you get the following error : "Only JSON and XML response/request body is supported to query the result"
You can reproduce the issue with this snippet:
```
POST https://cognito-idp.eu-west-1.amazonaws.com
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth
{
"AuthParameters" : {
"USERNAME" : "<user>",
"PASSWORD" : "<pwd>"
},
"AuthFlow" : "USER_PASSWORD_AUTH",
"ClientId" : "123456789"
}
@id_token = {{login.response.body.AuthenticationResult.IdToken}}
```
=> Fix isJSON for AWS content type

src/views/httpResponseWebview.ts
An update to highlight.js means that it has now started escaping quotes, which has broken the regex that is used to find and replace urls. This PR adds additional logic to remove the encoded characters from the link that gets generated
=> Fix issue with URL links picking up trailing quotes (fixes #816)

src/utils/aadV2TokenProvider.ts
{{$aadV2Token scopes:https://graph.windows.net/openid clientId:<clientId>  }}
fixes #698
=> #698 add :/ in scope regex to match

src/providers/fileVariableReferencesCodeLensProvider.ts
These changes aim to fix #883 by skipping comment lines when analysing variable blocks to show reference counts.
```http
@foo = abc
@bar = xyz
@quz=ijk
GET https://abc.xyz?foo={{foo}}&bar={{bar}}
```
I have no experience whatsoever with this codebase so I'm not sure wether changing this file is enough or other files need to be changed, but in my tests it worked as expected:
```http
@foo = abc
@bar = xyz
@quz=ijk
GET http://urlecho.appspot.com/echo?body={{foo}}+X+{{bar}}+X+{{bar}}
```
=> Allow comments between variable declarations

README.md, package-lock.json, package.json, src/models/configurationSettings.ts, src/views/httpResponseWebview.ts
Closes: #924 
(naive implementation, mostly as a proof of concept)
New behavior is toggle-able via useContentDispositionFilename setting (default true).
Only applies to "attachment" and "inline" disposition types (even though inline+filename response is not specifically following the syntax, it is often encountered in practice).
Note (on security): The extension does NOT sanitize the output filename and uses server-provided - equvalent of curl's --remote-header-name option).
=> SaveBody now uses filename from content-disposition

README.md, src/common/constants.ts, src/controllers/requestController.ts, src/models/requestMetadata.ts, src/providers/customVariableDiagnosticsProvider.ts, src/providers/httpCompletionItemProvider.ts, src/utils/httpElementFactory.ts, src/utils/selector.ts, src/utils/variableProcessor.ts, syntaxes/http.tmLanguage.json
`Prompt variable` is a variable that will prompt for user input every time user sending a request.
Some variables are meant to be changed all the time such as Session ID or OTP code.
Therefore, I think it is better to let the user input the designated value of that variable instead of changing the source code every time.
=> Add Prompt Variables

src/utils/aadV2TokenProvider.ts
$aadV2Token helper is using the same token even after it expires. This change removes the token from cache after the `expires_in` time expires.
=> Use token response expires_in to remove token from cache

snippets/http.json
standard post request Content-Type should be set to `application/json`
ref.: https://graphql.org/learn/serving-over-http/#post-request
=> add content type to graphql snippet

src/utils/httpVariableProviders/environmentVariableProvider.ts
Updated the environmentVariableProvider so that it supports variable resolution in all environments.
This is supposed to fix a few existing bugs and add more functionality by aligning environmentVariableResolution to be more similar to fileVariableResolution.
For example, the following settings:
```js
{
"rest-client.environmentVariables": {
"$shared": {
"protocol": "https",
"url": "{{$shared protocol}://www.demo.com",
},
"test": {
"apiEndpoint": "{{$shared url}/test/api",
"users": "{{$test apiEndpoint}}/users",
}
}
}
```
Before, it would resole to:
```
protocol = https
url = {{$shared protocol}://www.demo.com
apiEndpoint = {{$shared protocol}://www.demo.com
users = {{$test apiEndpoint}}/users
```
With this change it will be:
```
protocol = https
url = https://www.demo.com
apiEndpoint = …
```
=> Change EnvironmentVariable resolution

src/utils/httpRequestParser.ts
While RFC2616 indicates http header field `names` are case insensitive, it leaves http header field `values` more open to interpretation, such as using the text
> Applications ought to follow "common form", where one is known or
indicated, when generating HTTP constructs, since there might exist some implementations that fail to accept anything beyond the common forms.
This is a small user experience improvement for REST Client users to prevent a negative experience by using a case sensitive value.
This is also consistent with the current code snippet for getHeader method which forces lowercase on the http header fields. 
https://github.com/Huachao/vscode-restclient/blob/80ee7d19a9c9b61691a914170dbc750ac6d182f1/src/utils/misc.ts#L12
fixes #1236
=> feat(graphql): forces http header value to be lowercase

src/utils/userDataManager.ts
A follow up to [this](https://github.com/Huachao/vscode-restclient/pull/590) PR and [base-dir-spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
According to `environment.json` file content, i think, it looks like more a _**state**_, _**than**_ config, so i guess `environment.json` file should be placed in `XDG_STATE_HOME`.
Similar example: [moving state file from XDG_CONFIG_HOME to XDG_STATE_HOME](https://github.com/jesseduffield/lazygit/blob/618fe533f8c6113392eea981d03c65e6da5860bb/pkg/config/app_config.go#L292) ([context](https://github.com/jesseduffield/lazygit/pull/2936))
Also, added support of `VSC_REST_CLIENT_HOME` if single place for all user data required.
=> Make XDG directory specification support more convenient

README.md, src/utils/aadV2TokenProvider.ts
Hi @Huachao,
Thank you a lot for your work and such a great plugin. Looks very promising for me to use. 
I would like to suggest a very tiny PR with a feature. I found that all AAD settings can be set per environment except scopes. But on AAD, multiple app registrations can have different scopes (e.g. Dev/User.Default, Prod/User.Default, etc.). 
It would be awesome if you could approve my PR and add this feature to your extension. I wasn't able to build `vsix` package from your current master branch, so based it on a commit with tag `v0.25.0` and tested it on my local.
Thank you (;
=> [Feature] Read aad2 scopes from environment variables

src/controllers/historyController.ts, src/utils/misc.ts, src/views/httpResponseTextDocumentView.ts, src/views/httpResponseWebview.ts
This PR ungroups `Set-Cookie` headers since each header should appear independently. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie):
> To send multiple cookies, multiple `Set-Cookie` headers should be sent in the same response.
For example, the following is correct:
```
Set-Cookie: a=b
Set-Cookie: c=d
```
While the following is incorrect:
```
Set-Cookie: a=b,c=d
```
This PR achieves this by:
- Adding an exported `formatHeaders` function in `utils/misc.ts` that treats `set-cookie` as a special case.
- Removing the `private formatHeaders` function from `HttpResponseTextDocumentView` and updating all calls to use the new utility `formatHeaders` function.
- Removing the `private static formatHeaders` function from `HttpResponseWebview` and updating …
=> Preserve multiple `Set-Cookie` headers

src/utils/httpVariableProviders/systemVariableProvider.ts
This PR allows the users to create .env files for each environment that exists within their vscode settings. 
Behavior: When walking back up the path, when either `.env` or `.env.{vscode-env}` is found, stop and prefer `.env.{vscode-env}`.
Use case:
I want to specify an auth token in gitignored env files because the repo's settings.json is checked into source control already so we cannot place them in there safely.
Closes https://github.com/Huachao/vscode-restclient/issues/740
=> [Feature] add support for vscode env in dotenv
